# Generated by Django 4.2.14 on 2024-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile', models.TextField(blank=True, default='', null=True)),
                ('password', models.TextField()),
                ('bio', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
