# Generated by Django 4.2.14 on 2024-07-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usersecrets_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersecrets',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
