export { default as LandingPage } from "./LandingPage"
export { default as Login } from "./AuthPage/Login"
export { default as Register } from "./AuthPage/Register"
export { default as Unauthorized } from "./Unauthorized";
export { default as UserProfile } from "./UserProfile/UserProfile";
export { default as About } from "./About"
export { default as MyProfile } from "./MyProfile";
export { default as Deploy } from "./Deploy/Deploy";
export { default as Tokens } from "./Tokens/Tokens";