# Generated by Django 4.2.14 on 2024-07-30 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_alter_usersecrets_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBedrockModels',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model_id', models.TextField(blank=True, default='', null=True)),
                ('model_name', models.TextField(blank=True, default='', null=True)),
                ('input_modalities', models.TextField(blank=True, default='', null=True)),
                ('output_modalities', models.TextField(blank=True, default='', null=True)),
                ('local_path', models.TextField(blank=True, default='', null=True)),
                ('is_valid', models.BooleanField(blank=True, default=True, null=True)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
