# Generated by Django 4.2.14 on 2024-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbedrockmodels',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
