# Generated by Django 4.2.14 on 2024-07-31 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bedrock', '0002_userbedrockmodels_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbedrockmodels',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
